name: Build site, deploy to Azure, scan with Dastardly

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  scan-with-dastardly:
    name: Scan with Dastardly
    runs-on: ubuntu-latest
    needs: deploy-to-azure

    steps:
      - name: Run Dastardly Scan
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'https://ginandjuice.shop/'

      - name: Publish Dastardly Scan Report
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          check_name: 'Dastardly Scan Report'
          report_paths: '**/dastardly-report.xml'
          require_tests: true
